repos:
  - repo: local
    hooks:
      - id: clean-notebook
        name: Clean notebook cells
        entry: python scripts/clean_notebook.py
        language: python
        additional_dependencies:
          - nbformat
        files: \.ipynb$
  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean
        args:
          - --preserve-cell-metadata
          - id
          - --
