repos:
  - repo: local
    hooks:
      - id: clean-notebook
        name: Clean notebook cells
        entry: python scripts/clean_notebook.py
        language: python
        additional_dependencies:
          - nbformat
        files: \.ipynb$

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1  # use latest stable tag if available
    hooks:
      - id: nbstripout
        files: \.ipynb$

