name: Clean Notebooks

on:
  push:
    paths:
      - '**/*.ipynb'  # only trigger if a notebook was changed

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install nbstripout
        run: pip install nbstripout

      - name: Strip notebook outputs
        run: |
          nbstripout --install
          find . -name '*.ipynb' -exec nbstripout {} \; 

      - name: Run blob path check
        run: python scripts/check_blob_paths.py

      - name: Check for changes
        run: |
          git diff --exit-code || (
            echo "::error ::Notebooks need cleaning. Please run the cleaner."
            exit 1
          )
